name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: CI Job
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PUBLIC_FRONTEND_PORT: ${{ secrets.PUBLIC_FRONTEND_PORT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: 'latest'

      - name: Build and run services
        run: docker compose up -d --build

      - name: Wait for frontend to become healthy
        run: |
          echo "Waiting for frontend to become healthy..."
          for i in {1..30}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' frontend)
            if [ "$STATUS" = "healthy" ]; then
              echo "Frontend is healthy â€” system is up"
              exit 0
            fi
            sleep 5
          done

          echo "Frontend did not become healthy"
          docker compose logs
          exit 1

      - name: Shutdown
        if: always()
        run: docker compose down -v
